'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { useNSFW } from '@/contexts/nsfw-context'
import { useAuth } from '@/contexts/auth-context'
<<<<<<< HEAD
=======
import ImageWithFallback from '@/components/ui/image-with-fallback'
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
import { 
  ShoppingCart, 
  Eye, 
  Star, 
  Heart, 
  Share2, 
  Download,
  Package,
  User,
<<<<<<< HEAD
  Sparkles
=======
  Sparkles,
  Lock
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
} from 'lucide-react'

interface MarketplaceItem {
  id: string
  title: string
  description: string
  type: string
  category: string
  price: number
  currency: string
  status: string
  thumbnail?: string
  images?: string[]
  tags?: string[]
  isNsfw: boolean
  userId: string
  user?: {
    id: string
    name: string
    screenName?: string
    avatar?: string
    verified: boolean
  }
  reviews?: Array<{
    rating: number
    comment: string
    createdAt: string
    user: {
      name: string
      avatar?: string
    }
  }>
  _count?: {
    reviews: number
    orders: number
  }
  displayTitle?: string
  isAutoGenerated?: boolean
<<<<<<< HEAD
=======
  positivePrompt?: string
  negativePrompt?: string
  promptConfig?: any
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
}

interface MarketplaceItemCardProps {
  item: MarketplaceItem
  colors: {
    primary: string
    secondary: string
    accent: string
    bg: string
    particle: string
    cardBg: string
    cardBorder: string
    textPrimary: string
    textSecondary: string
    textLight: string
    textOnWhite: string
  }
}

export default function MarketplaceItemCard({ item, colors }: MarketplaceItemCardProps) {
  const { user } = useAuth()
  const nsfwContext = useNSFW()
  const isNSFW = nsfwContext?.isNSFW ?? false

<<<<<<< HEAD
  // Parse images field if it's a string
  const parsedImages = item.images ? (typeof item.images === 'string' ? JSON.parse(item.images) : item.images) : []
  
  // Parse tags field if it's a string
  const parsedTags = item.tags ? (typeof item.tags === 'string' ? JSON.parse(item.tags) : item.tags) : []
  
  // Add cache-busting timestamp to image URLs (skip data URLs)
  const getCacheBustedUrl = (url: string) => {
    if (!url) return url;
    
    // Don't add cache-busting to data URLs (they're already embedded)
    if (url.startsWith('data:image/svg+xml;base64,') || url.startsWith('data:')) {
      return url;
    }
    
    // For regular URLs, add cache-busting parameter
    const separator = url.includes('?') ? '&' : '?';
    return `${url}${separator}_cb=${Date.now()}`;
  }
  
  // Handle image loading errors
  const [imageError, setImageError] = useState(false)
  const [avatarError, setAvatarError] = useState(false)
  
  // Debug image loading
  const handleImageError = (error: React.SyntheticEvent<HTMLImageElement, Event>) => {
    const img = error.currentTarget;
    console.error('🖼️ CRITICAL: Image loading error - this should never happen with base64 SVGs:', {
      src: img.src.substring(0, 100) + '...',
      alt: img.alt,
      srcLength: img.src.length,
      isDataUrl: img.src.startsWith('data:'),
      isSvg: img.src.startsWith('data:image/svg+xml'),
      error: 'Image failed to load',
      timestamp: new Date().toISOString(),
      userAgent: navigator.userAgent
    });
    
    // Immediately report this error
    if (typeof window !== 'undefined' && window.fetch) {
      window.fetch('/api/marketplace/image-error', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          itemId: item.id,
          title: item.title,
          imageSrc: img.src,
          error: 'Base64 SVG failed to load'
        })
      }).catch(() => {
        // Silent fail for error reporting
      });
    }
    
    setImageError(true);
  }
  
  const handleImageLoad = (event: React.SyntheticEvent<HTMLImageElement, Event>) => {
    const img = event.currentTarget;
    console.log('✅ Image loaded successfully:', {
      src: img.src.substring(0, 50) + '...',
      alt: img.alt,
      naturalWidth: img.naturalWidth,
      naturalHeight: img.naturalHeight,
      isDataUrl: img.src.startsWith('data:'),
      isSvg: img.src.startsWith('data:image/svg+xml')
    });
  }
  
=======
  // Parse tags field if it's a string
  const parsedTags = item.tags ? (typeof item.tags === 'string' ? JSON.parse(item.tags) : item.tags) : []
  
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
  // Hide NSFW items in SFW mode
  if (item.isNsfw && !isNSFW) {
    return null
  }

<<<<<<< HEAD
=======
  // Get the best available image URL
  const getImageUrl = () => {
    // Try thumbnail first, then first image from images array
    let imageUrl = item.thumbnail
    
    if (!imageUrl && item.images && item.images.length > 0) {
      imageUrl = item.images[0]
    }
    
    return imageUrl
  }

  const imageUrl = getImageUrl()

>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
  // Calculate average rating
  const averageRating = item.reviews && item.reviews.length > 0 
    ? item.reviews.reduce((sum, review) => sum + review.rating, 0) / item.reviews.length 
    : 0

  const formatPrice = (price: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: item.currency || 'USD'
    }).format(price)
  }

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'AI_MODEL':
        return <Sparkles className="h-4 w-4" />
      case 'PROMPT':
        return <Package className="h-4 w-4" />
      case 'DIGITAL_GOOD':
        return <Download className="h-4 w-4" />
      default:
        return <Package className="h-4 w-4" />
    }
  }

  const getTypeLabel = (type: string) => {
    switch (type) {
      case 'AI_MODEL':
        return 'AI Model'
      case 'PROMPT':
        return 'Prompt'
      case 'DIGITAL_GOOD':
        return 'Digital Good'
      default:
        return type
    }
  }

  return (
    <Card 
<<<<<<< HEAD
      className="group overflow-hidden transition-all duration-300 hover:shadow-xl hover:scale-105"
=======
      className="group overflow-hidden transition-all duration-300 hover:shadow-xl hover:scale-105 w-full"
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
      style={{ 
        backgroundColor: colors.cardBg, 
        borderColor: colors.cardBorder,
        borderWidth: '1px'
      }}
    >
      <div className="relative">
        {/* Thumbnail */}
        <div className="aspect-square relative overflow-hidden bg-gradient-to-br from-gray-100 to-gray-200">
<<<<<<< HEAD
          {item.thumbnail && !imageError ? (
            <div className="relative w-full h-full">
              <img 
                src={item.thumbnail} 
                alt={item.displayTitle || item.title}
                className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110"
                onContextMenu={(e) => e.preventDefault()}
                onDragStart={(e) => e.preventDefault()}
                onLoad={handleImageLoad}
                onError={handleImageError}
              />
=======
          {imageUrl ? (
            <div className="relative w-full h-full">
              <ImageWithFallback
                src={imageUrl}
                alt={item.displayTitle || item.title}
                className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110"
                fallbackClassName="p-4"
                fallbackText="Image Not Available"
                retryCount={2}
              />
              
              {/* EDN Protected overlay */}
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
              <div className="absolute bottom-1 right-1 bg-black/60 text-white text-xs px-1 py-0.5 rounded opacity-70 pointer-events-none">
                EDN Protected
              </div>
            </div>
<<<<<<< HEAD
          ) : imageError ? (
            <div className="w-full h-full flex flex-col items-center justify-center p-4 bg-red-50">
              <div className="text-red-600 text-lg mb-2">⚠️</div>
              <div className="text-center">
                <div className="text-sm font-medium mb-1 text-red-800">
                  Image Loading Error
                </div>
                <div className="text-xs text-red-600">
                  Please refresh the page or contact support
                </div>
              </div>
            </div>
          ) : (
            <div className="w-full h-full flex flex-col items-center justify-center p-4">
              <Package className="h-16 w-16 mb-2" style={{ color: colors.primary }} />
              <div className="text-center">
                <div className="text-xs font-medium mb-1" style={{ color: colors.textPrimary }}>
                  {item.displayTitle || item.title}
                </div>
                <div className="text-xs" style={{ color: colors.textSecondary }}>
                  No image available
=======
          ) : (
            <div className="w-full h-full flex flex-col items-center justify-center p-4">
              <Package className="h-8 w-8 mb-2" style={{ color: colors.primary }} />
              <div className="text-center">
                <div className="text-xs font-medium mb-1" style={{ color: colors.textSecondary }}>
                  No Image Available
                </div>
                <div className="text-xs" style={{ color: colors.textLight }}>
                  {item.displayTitle || item.title}
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
                </div>
              </div>
            </div>
          )}
          
          {/* Overlay */}
          <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-all duration-300" />
          
          {/* Quick Actions */}
          <div className="absolute top-2 right-2 flex flex-col gap-2 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <Button 
              size="sm" 
              variant="secondary" 
              className="h-8 w-8 p-0 rounded-full"
              style={{ backgroundColor: colors.cardBg, borderColor: colors.cardBorder }}
            >
              <Heart className="h-4 w-4" />
            </Button>
            <Button 
              size="sm" 
              variant="secondary" 
              className="h-8 w-8 p-0 rounded-full"
              style={{ backgroundColor: colors.cardBg, borderColor: colors.cardBorder }}
            >
              <Share2 className="h-4 w-4" />
            </Button>
          </div>
          
          {/* Category Badge */}
          <div className="absolute top-2 left-2">
            <Badge 
              variant="secondary" 
              className="text-xs font-semibold"
              style={{ 
                backgroundColor: colors.primary, 
                color: colors.textOnWhite 
              }}
            >
              {getTypeLabel(item.type)}
            </Badge>
          </div>
          
          {/* NSFW Badge */}
          {item.isNsfw && (
            <div className="absolute bottom-2 left-2">
              <Badge 
                variant="destructive" 
                className="text-xs font-semibold"
              >
                NSFW
              </Badge>
            </div>
          )}
        </div>
      </div>

<<<<<<< HEAD
      <CardHeader className="pb-2">
        <div className="flex items-start justify-between gap-2">
          <div className="flex-1 min-w-0">
            <CardTitle 
              className="text-lg font-bold line-clamp-2 transition-colors duration-200 group-hover:text-blue-600"
=======
      <CardHeader className="pb-2 px-3">
        <div className="flex items-start justify-between gap-2">
          <div className="flex-1 min-w-0">
            <CardTitle 
              className="text-sm font-bold line-clamp-2 transition-colors duration-200 group-hover:text-blue-600"
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
              style={{ color: colors.textPrimary }}
            >
              {item.displayTitle || item.title}
            </CardTitle>
            <CardDescription 
<<<<<<< HEAD
              className="text-sm line-clamp-2 mt-1"
=======
              className="text-xs line-clamp-2 mt-1"
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
              style={{ color: colors.textSecondary }}
            >
              {item.description}
            </CardDescription>
          </div>
          <div className="flex flex-col items-end gap-1">
<<<<<<< HEAD
            <div className="text-lg font-bold" style={{ color: colors.primary }}>
=======
            <div className="text-sm font-bold" style={{ color: colors.primary }}>
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
              {formatPrice(item.price)}
            </div>
            {item._count?.orders && item._count.orders > 0 && (
              <div className="text-xs" style={{ color: colors.textLight }}>
                {item._count.orders} sold
              </div>
            )}
          </div>
        </div>
      </CardHeader>

<<<<<<< HEAD
      <CardContent className="pt-0">
        {/* Creator Info */}
        <div className="flex items-center gap-2 mb-3">
          {item.user?.avatar && !avatarError ? (
            <img 
              src={getCacheBustedUrl(item.user.avatar)} 
              alt={item.user.name} 
              className="w-6 h-6 rounded-full object-cover"
              onError={() => setAvatarError(true)}
            />
          ) : (
            <div className="w-6 h-6 rounded-full flex items-center justify-center" style={{ backgroundColor: colors.primary }}>
              <User className="h-3 w-3 text-white" />
            </div>
          )}
          <span className="text-sm font-medium truncate" style={{ color: colors.textSecondary }}>
=======
      <CardContent className="pt-0 px-3">
        {/* Creator Info */}
        <div className="flex items-center gap-2 mb-2">
          {item.user?.avatar ? (
            <img 
              src={item.user.avatar} 
              alt={item.user.name} 
              className="w-5 h-5 rounded-full object-cover"
            />
          ) : (
            <div className="w-5 h-5 rounded-full flex items-center justify-center" style={{ backgroundColor: colors.primary }}>
              <User className="h-2 w-2 text-white" />
            </div>
          )}
          <span className="text-xs font-medium truncate" style={{ color: colors.textSecondary }}>
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
            {item.user?.name || 'Unknown Creator'}
          </span>
          {item.user?.verified && (
            <Badge variant="outline" className="text-xs">
              ✓
            </Badge>
          )}
        </div>

        {/* Tags */}
        {parsedTags.length > 0 && (
<<<<<<< HEAD
          <div className="flex flex-wrap gap-1 mb-3">
            {parsedTags.slice(0, 3).map((tag, index) => (
=======
          <div className="flex flex-wrap gap-1 mb-2">
            {parsedTags.slice(0, 2).map((tag, index) => (
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
              <Badge 
                key={index} 
                variant="outline" 
                className="text-xs"
                style={{ 
                  borderColor: colors.cardBorder,
                  color: colors.textLight 
                }}
              >
                {tag}
              </Badge>
            ))}
<<<<<<< HEAD
            {parsedTags.length > 3 && (
=======
            {parsedTags.length > 2 && (
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
              <Badge 
                variant="outline" 
                className="text-xs"
                style={{ 
                  borderColor: colors.cardBorder,
                  color: colors.textLight 
                }}
              >
<<<<<<< HEAD
                +{parsedTags.length - 3}
=======
                +{parsedTags.length - 2}
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
              </Badge>
            )}
          </div>
        )}

<<<<<<< HEAD
        {/* Rating and Reviews */}
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-1">
            <Star className="h-4 w-4 fill-yellow-400 text-yellow-400" />
            <span className="text-sm font-medium" style={{ color: colors.textPrimary }}>
=======
        {/* Prompt Preview (only for AI_MODEL and PROMPT types) */}
        {(item.type === 'AI_MODEL' || item.type === 'PROMPT') && (item.positivePrompt || item.negativePrompt) && (
          <div className="mb-2">
            <div className="flex items-center gap-1 mb-1">
              <Lock className="h-3 w-3" style={{ color: colors.textLight }} />
              <span className="text-xs font-medium" style={{ color: colors.textSecondary }}>
                Prompt Preview
              </span>
            </div>
            <div 
              className="text-xs p-1.5 rounded border bg-opacity-50 backdrop-blur-sm transition-all duration-300"
              style={{
                backgroundColor: colors.cardBg,
                borderColor: colors.cardBorder,
                filter: 'blur(4px)',
                userSelect: 'none',
                pointerEvents: 'none' as const
              }}
            >
              {item.positivePrompt ? 
                item.positivePrompt.substring(0, 40) + (item.positivePrompt.length > 40 ? '...' : '') : 
                item.negativePrompt?.substring(0, 40) + (item.negativePrompt.length > 40 ? '...' : '')
              }
            </div>
            <div className="text-xs text-gray-500 dark:text-gray-400 mt-1 italic" style={{ color: colors.textLight }}>
              Full prompt and config available after purchase
            </div>
          </div>
        )}

        {/* Rating and Reviews */}
        <div className="flex items-center justify-between mb-3">
          <div className="flex items-center gap-1">
            <Star className="h-3 w-3 fill-yellow-400 text-yellow-400" />
            <span className="text-xs font-medium" style={{ color: colors.textPrimary }}>
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
              {averageRating > 0 ? averageRating.toFixed(1) : 'New'}
            </span>
            {item._count?.reviews && item._count.reviews > 0 && (
              <span className="text-xs" style={{ color: colors.textLight }}>
                ({item._count.reviews})
              </span>
            )}
          </div>
          
          <div className="flex items-center gap-1 text-xs" style={{ color: colors.textLight }}>
            {getTypeIcon(item.type)}
            <span>{getTypeLabel(item.type)}</span>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex gap-2">
          <Link href={`/marketplace/${item.id}`} className="flex-1">
            <Button 
              variant="outline" 
<<<<<<< HEAD
              className="w-full text-sm"
=======
              className="w-full text-xs h-8"
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
              style={{ 
                borderColor: colors.primary,
                color: colors.primary 
              }}
            >
<<<<<<< HEAD
              <Eye className="h-4 w-4 mr-2" />
              View Details
=======
              <Eye className="h-3 w-3 mr-1" />
              View
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
            </Button>
          </Link>
          
          <Button 
<<<<<<< HEAD
            className="flex-1 text-sm"
=======
            className="flex-1 text-xs h-8"
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
            style={{ 
              backgroundColor: colors.primary, 
              color: colors.textOnWhite 
            }}
          >
<<<<<<< HEAD
            <ShoppingCart className="h-4 w-4 mr-2" />
            Buy Now
=======
            <ShoppingCart className="h-3 w-3 mr-1" />
            Buy
>>>>>>> 5f0a3f67cc9176021538ab562209642046544539
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}