'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { useNSFW } from '@/contexts/nsfw-context'
import { useAuth } from '@/contexts/auth-context'
import ImageWithFallback from '@/components/ui/image-with-fallback'
import { 
  ShoppingCart, 
  Eye, 
  Star, 
  Heart, 
  Share2, 
  Download,
  Package,
  User,
  Sparkles
} from 'lucide-react'

interface MarketplaceItem {
  id: string
  title: string
  description: string
  type: string
  category: string
  price: number
  currency: string
  status: string
  thumbnail?: string
  images?: string[]
  tags?: string[]
  isNsfw: boolean
  userId: string
  user?: {
    id: string
    name: string
    screenName?: string
    avatar?: string
    verified: boolean
  }
  reviews?: Array<{
    rating: number
    comment: string
    createdAt: string
    user: {
      name: string
      avatar?: string
    }
  }>
  _count?: {
    reviews: number
    orders: number
  }
  displayTitle?: string
  isAutoGenerated?: boolean
}

interface MarketplaceItemCardProps {
  item: MarketplaceItem
  colors: {
    primary: string
    secondary: string
    accent: string
    bg: string
    particle: string
    cardBg: string
    cardBorder: string
    textPrimary: string
    textSecondary: string
    textLight: string
    textOnWhite: string
  }
}

export default function MarketplaceItemCard({ item, colors }: MarketplaceItemCardProps) {
  const { user } = useAuth()
  const nsfwContext = useNSFW()
  const isNSFW = nsfwContext?.isNSFW ?? false

  // Parse images field if it's a string
  const parsedImages = item.images ? (typeof item.images === 'string' ? JSON.parse(item.images) : item.images) : []
  
  // Parse tags field if it's a string
  const parsedTags = item.tags ? (typeof item.tags === 'string' ? JSON.parse(item.tags) : item.tags) : []
  
  // Hide NSFW items in SFW mode
  if (item.isNsfw && !isNSFW) {
    return null
  }

  // Get the best available image URL
  const getImageUrl = () => {
    // Try thumbnail first, then first image from images array
    let imageUrl = item.thumbnail
    
    if (!imageUrl && parsedImages.length > 0) {
      imageUrl = parsedImages[0]
    }
    
    return imageUrl
  }

  const imageUrl = getImageUrl()

  // Calculate average rating
  const averageRating = item.reviews && item.reviews.length > 0 
    ? item.reviews.reduce((sum, review) => sum + review.rating, 0) / item.reviews.length 
    : 0

  const formatPrice = (price: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: item.currency || 'USD'
    }).format(price)
  }

  const getTypeIcon = (type: string) => {
    switch (type) {
      case 'AI_MODEL':
        return <Sparkles className="h-4 w-4" />
      case 'PROMPT':
        return <Package className="h-4 w-4" />
      case 'DIGITAL_GOOD':
        return <Download className="h-4 w-4" />
      default:
        return <Package className="h-4 w-4" />
    }
  }

  const getTypeLabel = (type: string) => {
    switch (type) {
      case 'AI_MODEL':
        return 'AI Model'
      case 'PROMPT':
        return 'Prompt'
      case 'DIGITAL_GOOD':
        return 'Digital Good'
      default:
        return type
    }
  }

  return (
    <Card 
      className="group overflow-hidden transition-all duration-300 hover:shadow-xl hover:scale-105"
      style={{ 
        backgroundColor: colors.cardBg, 
        borderColor: colors.cardBorder,
        borderWidth: '1px'
      }}
    >
      <div className="relative">
        {/* Thumbnail */}
        <div className="aspect-square relative overflow-hidden bg-gradient-to-br from-gray-100 to-gray-200">
          {imageUrl ? (
            <div className="relative w-full h-full">
              <ImageWithFallback
                src={imageUrl}
                alt={item.displayTitle || item.title}
                className="w-full h-full object-cover transition-transform duration-300 group-hover:scale-110"
                fallbackClassName="p-4"
                fallbackText="Image Not Available"
                retryCount={2}
              />
              
              {/* EDN Protected overlay */}
              <div className="absolute bottom-1 right-1 bg-black/60 text-white text-xs px-1 py-0.5 rounded opacity-70 pointer-events-none">
                EDN Protected
              </div>
            </div>
          ) : (
            <div className="w-full h-full flex flex-col items-center justify-center p-4">
              <Package className="h-12 w-12 mb-2" style={{ color: colors.primary }} />
              <div className="text-center">
                <div className="text-sm font-medium mb-1" style={{ color: colors.textSecondary }}>
                  No Image Available
                </div>
                <div className="text-xs" style={{ color: colors.textLight }}>
                  {item.displayTitle || item.title}
                </div>
              </div>
            </div>
          )}
          
          {/* Overlay */}
          <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-all duration-300" />
          
          {/* Quick Actions */}
          <div className="absolute top-2 right-2 flex flex-col gap-2 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
            <Button 
              size="sm" 
              variant="secondary" 
              className="h-8 w-8 p-0 rounded-full"
              style={{ backgroundColor: colors.cardBg, borderColor: colors.cardBorder }}
            >
              <Heart className="h-4 w-4" />
            </Button>
            <Button 
              size="sm" 
              variant="secondary" 
              className="h-8 w-8 p-0 rounded-full"
              style={{ backgroundColor: colors.cardBg, borderColor: colors.cardBorder }}
            >
              <Share2 className="h-4 w-4" />
            </Button>
          </div>
          
          {/* Category Badge */}
          <div className="absolute top-2 left-2">
            <Badge 
              variant="secondary" 
              className="text-xs font-semibold"
              style={{ 
                backgroundColor: colors.primary, 
                color: colors.textOnWhite 
              }}
            >
              {getTypeLabel(item.type)}
            </Badge>
          </div>
          
          {/* NSFW Badge */}
          {item.isNsfw && (
            <div className="absolute bottom-2 left-2">
              <Badge 
                variant="destructive" 
                className="text-xs font-semibold"
              >
                NSFW
              </Badge>
            </div>
          )}
        </div>
      </div>

      <CardHeader className="pb-2">
        <div className="flex items-start justify-between gap-2">
          <div className="flex-1 min-w-0">
            <CardTitle 
              className="text-lg font-bold line-clamp-2 transition-colors duration-200 group-hover:text-blue-600"
              style={{ color: colors.textPrimary }}
            >
              {item.displayTitle || item.title}
            </CardTitle>
            <CardDescription 
              className="text-sm line-clamp-2 mt-1"
              style={{ color: colors.textSecondary }}
            >
              {item.description}
            </CardDescription>
          </div>
          <div className="flex flex-col items-end gap-1">
            <div className="text-lg font-bold" style={{ color: colors.primary }}>
              {formatPrice(item.price)}
            </div>
            {item._count?.orders && item._count.orders > 0 && (
              <div className="text-xs" style={{ color: colors.textLight }}>
                {item._count.orders} sold
              </div>
            )}
          </div>
        </div>
      </CardHeader>

      <CardContent className="pt-0">
        {/* Creator Info */}
        <div className="flex items-center gap-2 mb-3">
          {item.user?.avatar ? (
            <img 
              src={item.user.avatar} 
              alt={item.user.name} 
              className="w-6 h-6 rounded-full object-cover"
            />
          ) : (
            <div className="w-6 h-6 rounded-full flex items-center justify-center" style={{ backgroundColor: colors.primary }}>
              <User className="h-3 w-3 text-white" />
            </div>
          )}
          <span className="text-sm font-medium truncate" style={{ color: colors.textSecondary }}>
            {item.user?.name || 'Unknown Creator'}
          </span>
          {item.user?.verified && (
            <Badge variant="outline" className="text-xs">
              ✓
            </Badge>
          )}
        </div>

        {/* Tags */}
        {parsedTags.length > 0 && (
          <div className="flex flex-wrap gap-1 mb-3">
            {parsedTags.slice(0, 3).map((tag, index) => (
              <Badge 
                key={index} 
                variant="outline" 
                className="text-xs"
                style={{ 
                  borderColor: colors.cardBorder,
                  color: colors.textLight 
                }}
              >
                {tag}
              </Badge>
            ))}
            {parsedTags.length > 3 && (
              <Badge 
                variant="outline" 
                className="text-xs"
                style={{ 
                  borderColor: colors.cardBorder,
                  color: colors.textLight 
                }}
              >
                +{parsedTags.length - 3}
              </Badge>
            )}
          </div>
        )}

        {/* Rating and Reviews */}
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-1">
            <Star className="h-4 w-4 fill-yellow-400 text-yellow-400" />
            <span className="text-sm font-medium" style={{ color: colors.textPrimary }}>
              {averageRating > 0 ? averageRating.toFixed(1) : 'New'}
            </span>
            {item._count?.reviews && item._count.reviews > 0 && (
              <span className="text-xs" style={{ color: colors.textLight }}>
                ({item._count.reviews})
              </span>
            )}
          </div>
          
          <div className="flex items-center gap-1 text-xs" style={{ color: colors.textLight }}>
            {getTypeIcon(item.type)}
            <span>{getTypeLabel(item.type)}</span>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex gap-2">
          <Link href={`/marketplace/${item.id}`} className="flex-1">
            <Button 
              variant="outline" 
              className="w-full text-sm"
              style={{ 
                borderColor: colors.primary,
                color: colors.primary 
              }}
            >
              <Eye className="h-4 w-4 mr-2" />
              View Details
            </Button>
          </Link>
          
          <Button 
            className="flex-1 text-sm"
            style={{ 
              backgroundColor: colors.primary, 
              color: colors.textOnWhite 
            }}
          >
            <ShoppingCart className="h-4 w-4 mr-2" />
            Buy Now
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}